language: cpp
compiler:
    - gcc

before_install:
    - sudo apt-get update
    - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y 

install: 
    - sudo apt-get update
    - sudo apt-get install qtdeclarative5-dev qt5-default

script:
    - qmake -o Makefile rampage.pro
    - make
    - make clean
