language: cpp
compiler:
    - gcc

before_install:
    - sudo apt-get update
    - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y
    - sudo apt-get -y install debhelper cdbs lintian build-essential fakeroot devscripts pbuilder dh-make debootstrap

install:
    - sudo apt-get update
    - sudo apt-get -y install qtdeclarative5-dev qt5-default python
    - sudo apt-get remove cmake
    - sudo add-apt-repository -y ppa:andykimpe/cmake3
    - sudo apt-get update
    - sudo apt-get install cmake3 

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
