language: cpp
compiler:
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:andykimpe/cmake3
    - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
    - sudo apt-get -q update

install:
    - sudo apt-get remove cmake
    - sudo apt-get -y -q install debhelper cdbs lintian build-essential fakeroot devscripts pbuilder dh-make debootstrap qtdeclarative5-dev qt5-default python cmake3

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
