language: cpp
compiler:
    - gcc

install:
    - sudo apt-get update
    - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y
    - sudo apt-get install tar libarchive-dev qt5declarative-dev qt5-default python
    - sudo apt-get -y install debhelper cdbs lintian build-essential fakeroot devscripts pbuilder dh-make debootstrap
    - sudo apt-get remove cmake
    - sudo add-apt-repository -y ppa:andykimpe/cmake3
    - sudo apt-get update
    - sudo apt-get install cmake3
      #    - wget http://www.cmake.org/files/v2.8/cmake-2.8.11.tar.gz
      #    - tar -xzvf cmake-2.8.11.tar.gz
      #    - cd cmake-2.8.11
      #    - ./bootstrap --prefix=/user --system-libs --mandir=/share/man --docdir=/share/doc/cmake-2.8.11
      #    - make
      #    - sudo make install 

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
