language: cpp
compiler:
    - gcc

install:
    - sudo apt-get update
    - sudo apt-get install qt5-default qttools5-dev-tools

script:
    - qmake -o Makefile rampage.pro
    - make
    - make clean
